package com.keita.module3;

import java.util.Scanner;

public class RPSGame{

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int random;

        // uScore and cScore are local variables and they are
        // going to be use to store the user score or computer
        // in them.
        int uScore = 0;
        int cScore = 0;

        // This cPRS variable is going to be use to assign rock, paper or
        // scissors base on what number the computer generate
        String cRPS;

        // This is how many time we going to play the game
        int roundPlay = 3;

        // Notice that we are using the while loop instead of a
        // for loop. Inside the While loop parentheses as long
        // the statement the variable roundPlay is not equal to 0
        // the while loop will not end.
        while (roundPlay != 0) {
            random = (int) (Math.random() * 3 + 1);
            System.out.println("Please enter rock, paper, or scissors using lower case letters: ");
            String userGuess = sc.nextLine();

            // We check if the number generated by the computer is 1
            // and we assign Rock to the variable cRPS
            if (random == 1) {
                cRPS = "rock";
            } else if (random == 2) {
                cRPS = "paper";
            } else {
                cRPS = "scissors";
            }

            // Here we check if cRPS value is equal to user input
            // and we increment user score by 5 point and we decrement
            // roundPlay by 1. If we don't decrement the roundPlay variable
            // it value will away stay at 3, and the while loop will never end.
            if (cRPS.equals("paper") && userGuess.equals("rock")) {
                System.out.println("Computer's choice was paper\n" +
                        "User's choice was rock.\n" +
                        "Paper covers rock.\n" +
                        "The computer wins!");
                cScore++;
                roundPlay--;
            }else if (userGuess.equals("rock") && cRPS.equals("paper")) {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + ".\n" +
                        "Paper covers rock.\n" +
                        "The user wins!");
                uScore++;
                roundPlay--;
            }else if (cRPS.equals("rock") && userGuess.equals("scissors")) {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + ".\n" +
                        "Rock crushes scissors.\n" +
                        "The computer wins!");
                cScore++;
                roundPlay--;
            }
            else if (cRPS.equals("scissors") && userGuess.equals("rock")) {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + ".\n" +
                        "Rock crushes scissors.\n" +
                        "The user wins!");
                uScore++;
                roundPlay--;
            }
            else if (cRPS.equals("scissors") && userGuess.equals("paper")) {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + ".\n" +
                        "Scissors can cut paper.\n" +
                        "The computer wins!");
                cScore++;
                roundPlay--;
            }
            else if (cRPS.equals("paper") && userGuess.equals("scissors")) {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + ".\n" +
                        "Scissors can cut paper.\n" +
                        "The user wins!");
                uScore++;
                roundPlay--;
            }
            else {
                System.out.println("Computer's choice was " + cRPS + "\n" +
                        "User's choice was " + userGuess + "\n" +
                        "It is a tie. No one wins!!");
                roundPlay--;
            }
            System.out.println();
        }
        System.out.println("\nThe user won " + uScore + " times and the computer won " + cScore + " times.");
    }
}
